---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Only update hashicorp-owned actions
    # External actions managed via TSCCR
    groups:
      github-actions-breaking:
        update-types:
          - major
      github-actions-backward-compatible:
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory:
    schedule:
      interval: weekly
