name: Reproducible Build
author: Release Engineering <team-rel-eng@hashicorp.com>
description: Define a reproducible build. Currently only supports Go builds.

inputs:
  instructions:
    description: |
      Build instructions to generate the product binary.
      This is a bash script, and it will have the following environment variables
      set that you can refer to in the script...
      TARGET_DIR        - The directory where all build output must be placed (this directory is zipped up to form the zip package).
      BIN_NAME          - The name of the binary specified in BIN_NAME.
      GOOS and OS       - The OS specified in the `os` input.
      GOARCH and ARCH   - The architecture specified in the `arch` input.
      PRODUCT_VERSION   - The version of the product being built.
      PRODUCT_REVISION  - The commit SHA of the product being built.
    required: true

  go_version:
    description: Version of Go to use for this build.
    required: true

  product_version:
    description: Version of the product being built.
    required: true

  os:
    description: Target product operating system.
    required: true

  arch:
    description: Target product architecture.
    required: true

  package_name:
    description: Name of the package to build. Used to calculate default bin_name and zip_name.
    required: true

  bin_name:
    description: Name of the product binary generated by instructions.
    required: false

  zip_name:
    description: Name of the product zip file.
    required: false

runs:
  using: composite
  steps:
    - name: Calculate default values and paths; set env vars.
      shell: bash
      env:
        INSTRUCTIONS: ${{ inputs.instructions }}
        OS: ${{ inputs.os }}
        ARCH: ${{ inputs.arch }}
        GOOS: ${{ inputs.os }}
        GOARCH: ${{ inputs.arch }}
        PRODUCT_VERSION: ${{ inputs.product_version }}
        BIN_NAME: ${{ inputs.bin_name }}
        ZIP_NAME: ${{ inputs.zip_name }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: ./scripts/calculate-defaults-and-paths
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go_version }}
    - name: Run Primary Build
      shell: bash
      run: ./scripts/primary-build
    - name: Run Local Verification Build
      shell: bash
      run: ./scripts/local-verification-build
    - name: Compare Build Outputs
      shell: bash
      run: ./scripts/compare-digests
