#!/usr/bin/env bash

# Calculate an ID for the current state of the work tree.
#
# Take the hashes of git diff and git diff --staged and the HEAD
# commit ID, then take the hash of them all together.

set -Eeuo pipefail

sha() { cat - | sha256sum | cut -d' ' -f1; }

nonempty_diff_sha() { local NAME="git diff $*"
	SHA="<empty>"
	D="$(git diff --exit-code "$@")" || {
		SHA="$(sha <<< "$D")"
	}
	echo "$SHA"
}

{
	git rev-parse HEAD
	nonempty_diff_sha
	nonempty_diff_sha --staged
} | sha
