#!/usr/bin/env bash

set -Eeuo pipefail

log() { echo "==> $*" 1>&2; }
die() { log "FATAL: $*"; return 1; }

VERSION="$(cat dev/VERSION)"

# Set TAGS to vX.Y.Z, vX.Y, and vX
TAGS=("v$VERSION" "v${VERSION%\.*}" "v${VERSION%%\.*}")

FULL_TAG="${TAGS[0]}"

for TAG in "${TAGS[@]}"; do
	echo "$TAG"
done

if (git tag | grep -F "$FULL_TAG"); then
	die "Full tag '$FULL_TAG' already exists. Please increment the version first."
fi

for TAG in "${TAGS[@]}"; do
	log "Tagging and pushing as $TAG"
	git tag -f "$TAG"
	# We don't want to run pre-push hooks for tags
	# beause we only tag known-good versions.
	git push --no-verify -f origin "$TAG"
done

log "Getting release notes..."
export TAG="$FULL_TAG"
export VERSION="$FULL_TAG"
export REPO_URL="https://github.com/hashicorp/actions-go-build"
NOTES="$(envsubst < "dev/changes/$FULL_TAG.md")"

log "Creating GitHub release..."
gh release create "$FULL_TAG" --notes "$NOTES"

# If no release zips were passed, we're done.
[[ "${#@}" -eq 0 ]] && exit 0

# If a list of zip files was passed, upload them as release assets.

SHASUMSFILE="actions-go-build_${VERSION}_SHA256SUMS"
sha256sum "$@" > "$SHASUMSFILE"
gh release upload "$FULL_TAG" "$@"
