#!/usr/bin/env bash

set -Eeuo pipefail

source dev/docs/markdown_table.bash
source scripts/build_env.bash


build_env_with_pipes() {
	print_build_env | sed -E 's/^([^[:space:]]+[[:space:]]+)(.*)/\1 | \2/g'
}

read_output_to_array ROW_DATA build_env_with_pipes

HEADERS=("Name" "Description")

write_env_rows() {
	for ROW in "${ROW_DATA[@]}"; do
		write_env_row "$ROW"
	done
}

write_env_row() {
	local DATA="$1"
	local NAME
	local DESC
	NAME="$(cut -d'|' -f1 <<< "$DATA" | xargs)"
	DESC="$(cut -d'|' -f2 <<< "$DATA" | xargs)"
	write_row "\`$NAME\`" "$DESC"
}

markdown_table write_header write_env_rows
