#!/usr/bin/env bash

# shellcheck disable=SC2002 # It reads better using pipes.

set -Eeuo pipefail

TITLES="$(cat README.md | grep -E '^#{2,3} .*$' | sed -E -e 's/#/  /g' -e 's/^    //g' -e 's/^( +)/\1- /g' -e 's/( +)- (.*$)/\1* [\2]/g')"

LINKS="$(cat README.md | grep -E '^#{2,3} .*$' | tr ' ,()' '-' | tr '[:upper:]' '[:lower:]' | sed -E 's/^#+-(.*)$/(#\1)/g')"

pr -m -t <(echo "$TITLES") <(echo "$LINKS") | sed -E -e 's/\][[:space:]]+\(/](/g' -e 's/^ //g'
