#!/usr/bin/env bash

set -Eeuo pipefail

# Set up a shell isolated from system config
# and using dotgit instead of .git
#
# This can be used to modify the checked-in git
# repo we use for testing.

export HOME=/nowhere
export XGD_CONFIG_HOME=/nowhere
export GIT_DIR=dotgit

"$SHELL"
