name: Verify A Build Result
author: Release Engineering <team-rel-eng@hashicorp.com>
description: Verify a reproducible build result.

inputs:

  result_file:
    description: The result file we're trying to verify.
    required: true

  debug:
    description: Enable debug-level logging.
    required: false
    default: false

runs:
  using: composite
  steps:

    # Setup Go for CLI compilation.
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Set some needed environment variables.
      shell: bash
      run: |
        # Set environment.
        ACTION_ROOT="${{ github.action_path }}/.."
        {
          echo "TMPDIR=$RUNNER_TEMP"
          echo "ACTION_ROOT=$ACTION_ROOT"
          echo "RUN=$ACTION_ROOT/scripts/gha run"
          echo "RUN_CLI=env DEBUG=${{ inputs.debug }} $ACTION_ROOT/scripts/gha run actions-go-build"
          echo "RESULT_FILE=${{ inputs.result_file }}"
          echo "VERIFICATION_RESULT=$RUNNER_TEMP/verification-result.json"
        } >> "$GITHUB_ENV"

    # Compile the CLI inline. We should work to remove this step by using
    # precompiled binaries for tagged versions (maybe stored as release
    # assets).
    - name: Install the CLI
      shell: bash
      working-directory: ${{ env.ACTION_ROOT }}
      run: |
        # Install the CLI
        $RUN make install

    # Read build config
    - name: Read config from result file.
      shell: bash
      run: |
        # Read some values from the build config.
        GO_VERSION="$(actions-go-build inspect -q -go-version "$RESULT_FILE")"
        echo "GO_VERSION=$GO_VERSION" | tee >> "$GITHUB_ENV"

        REPRODUCIBLE="$(actions-go-build inspect -q -reproducible "$RESULT_FILE")"
        echo "REPRODUCIBLE=$REPRODUCIBLE" | tee >> "$GITHUB_ENV"

    # Print build config.
    - name: Print build config
      shell: bash
      run: |
        # Print build config.
        $RUN_CLI inspect -build-config "$RESULT_FILE"

    # Setup Go For Running the Verification Build
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    # Verify Reproducibility
    - name: Verify Reproducibility
      if: env.REPRODUCIBLE != 'false'
      shell: bash
      working-directory: ${{ inputs.work_dir }}
      run: |
        # Run verification, fail workflow on verification failure (reproducible == true).
        $RUN_CLI verify -json "$RESULT_FILE" | tee > "$VERIFICATION_RESULT"

    # Report Reproducibility
    - name: Report Reproducibility
      if: env.REPRODUCIBLE == 'false'
      shell: bash
      working-directory: ${{ inputs.work_dir }}
      run: |
        # Run verification, report result but do not fail (reproducible == false).
        $RUN_CLI verify -json "$RESULT_FILE" | tee > "$VERIFICATION_RESULT" || true

    # Store reproducibility report.
    - name: Upload Reproducibility Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.VERIFICATION_RESULT }}
        if-no-files-found: error
