#!/usr/bin/env bash

# shellcheck disable=SC2034 # Don't check unused vars for the sake of the store_env function.

source scripts/standard-header.bash

store_env() {
  {
    echo "$1<<EOF"
    echo "${!1}"
    echo "EOF"
  } >> "$GITHUB_ENV"
  echo "export $1='${!1}'" >> "$GITHUB_ENV.export"
  echo "--> Set $1 to '${!1}'"
}

# Pass through env vars from required inputs.
store_env INSTRUCTIONS
store_env OS
store_env ARCH
store_env PRODUCT_VERSION

GOOS="$OS"
store_env GOOS

GOARCH="$ARCH"
store_env GOARCH

BUILD_BASE_DIR="dist/$OS/$ARCH"

TARGET_DIR="$BUILD_BASE_DIR/build"
store_env TARGET_DIR

ZIP_DIR="$BUILD_BASE_DIR/dist"
store_env ZIP_DIR

META_DIR="$BUILD_BASE_DIR/meta"
store_env META_DIR

PRIMARY_ROOT_DIR="$(pwd)"
store_env PRIMARY_ROOT_DIR

LOCAL_VERIFICATION_ROOT_DIR="$PRIMARY_ROOT_DIR/../local-verification"
store_env LOCAL_VERIFICATION_ROOT_DIR

# Default BIN_NAME is package name minus -enteprise suffix.
[ -z "$BIN_NAME" ] && { BIN_NAME="${PACKAGE_NAME%-enterprise}"; }
store_env BIN_NAME

[ -z "$ZIP_NAME" ] && { ZIP_NAME="${PACKAGE_NAME}_${PRODUCT_VERSION}_${OS}_${ARCH}.zip"; }
store_env ZIP_NAME

PRODUCT_REVISION="$(git rev-parse HEAD)"
store_env PRODUCT_REVISION

BIN_PATH="$TARGET_DIR/$BIN_NAME"
store_env BIN_PATH

ZIP_PATH="$ZIP_DIR"
store_env ZIP_PATH
