#!/usr/bin/env bash

# shellcheck disable=SC2207 # I want BIN_RESULTS and ZIP_RESULTS to word-split into arrays.

source scripts/standard_header.bash
source scripts/digest_tools.bash

PASSED=true
BIN_PASSED=true
ZIP_PASSED=true

BIN_RESULTS=($(compare_digest "bin")) || { PASSED=false; BIN_PASSED=false; }
ZIP_RESULTS=($(compare_digest "zip")) || { PASSED=false; ZIP_PASSED=false; }

# Execute 'true' or 'false' on exit to set the correct exit code.
trap '$PASSED' EXIT

write_summary() { echo "$*" >> "${GITHUB_STEP_SUMMARY:-github-step-summary.md}"; }

emoji_for_passed() { "$1" && echo ":white_check_mark:" || echo ":x:"; }

print_results() {
	local NAME="$1"; shift
	local PASSED="$1"; shift
	local RESULTS=("$@")
	if $PASSED; then
		write_summary "$(emoji_for_passed "$PASSED") $NAME SHA256 sums match: ${RESULTS[0]}"
	else
		write_summary "$(emoji_for_passed "$PASSED") $NAME SHA256 sums do not match:"
		write_summary "|                          |      SHA256     |"
		write_summary "|--------------------------|-----------------|"
		write_summary "| Primary build            | ${RESULTS[0]}   |"
		write_summary "| Local verification build | ${RESULTS[1]:-} |"
	fi
}

write_summary "### Local Verification Build $(emoji_for_passed "$PASSED")"

print_results "Binary" $BIN_PASSED "${BIN_RESULTS[@]}"
print_results "Zip"    $ZIP_PASSED "${ZIP_RESULTS[@]}"
