#!/usr/bin/env bash

set -Eeuo pipefail

log() { echo "$*" 1>&2; }
debug() { { [[ "${DEBUG:-}" == "true" ]] && log "$*"; } || true; }

group() {
	debug "Group starting: $*"
	log "::group::$*" 1>&2
}

endgroup() {
	debug "Group ending."
	log "::endgroup::" 1>&2
}

run() {
	group "Run $*"
	trap 'endgroup; trap - RETURN' RETURN
	"$@" || return 1
	return 0
}

F="${1:-}"

[[ -n "$F" ]] || exit 0

shift

"$F" "$@"
