#!/usr/bin/env bash

# This script asserts that a GitHub Action step failed correctly.
#
# It assumes that the variable WHEN is a description of the condition being tested.
# It assumes that its single arg is set to the ${{ steps.<step_id>.outcome }}
# of the step being tested.

set -Eeuo pipefail

source scripts/standard_header.bash

[ "$1" = "failure" ] || die ":x: Action succeeded unexpectedly when ${WHEN}."
log ":white_check_mark: Action failed correctly when ${WHEN}"
