#!/usr/bin/env bash

# shellcheck source=scripts/standard_header.bash
source "${BASH_SOURCE%/*}/standard_header.bash"

# shellcheck source=scripts/build.bash
source "${BASH_SOURCE%/*}/build.bash"

log
log "Beginning local verification build."
log

log "Creating local verification build environment."

make_and_enter_isolated_build_env "$VERIFICATION_BUILD_ROOT"

SLEEP_SECONDS=5

log "Waiting $SLEEP_SECONDS seconds to try to trigger temporal nondeterminism..."
sleep $SLEEP_SECONDS

log "Sleep over, running build..."
build
