#!/usr/bin/env bash

# shellcheck source=scripts/build.bash
source "${BASH_SOURCE%/*}/build.bash"

# We assume this script is started in the repo root.

make_and_enter_isolated_build_env "$VERIFICATION_BUILD_ROOT"

build
