#!/usr/bin/env bash

# shellcheck source=scripts/standard_header.bash
source "${BASH_SOURCE%/*}/standard_header.bash"

# shellcheck source=scripts/build.bash
source "${BASH_SOURCE%/*}/build.bash"


log
log "Beginning primary build."
log

build
