name: Action Test
on:
  workflow_call:
    inputs:

      when:
        type: string
        required: true
      assert:
        type: string
        required: true
      instructions:
        type: string
        required: true

      runs-on:
        type: string
        default: ubuntu-latest
        required: false
      reproducible:
        type: string
        default: assert
        required: false
      product_name:
        type: string
        default: example-app
        required: false
      product_version:
        type: string
        default: 1.0.0
        required: false
      go_version:
        type: string
        default: 1.17
        required: false
      os:
        type: string
        default: linux
        required: false
      arch:
        type: string
        default: amd64
        required: false

jobs:
  action-test:
    name: Assert ${{ inputs.assert }}
    runs-on: ${{ inputs.runs-on }}
    env:
      WHEN: ${{ inputs.when }}
    steps:
      - if: inputs.assert != 'success' && inputs.assert != 'failure'
        run: |
          echo "assert must be one of: 'success' or 'failure'"
          exit 1
      - uses: actions/checkout@v3
      - name: Invoke actions-go-build when ${{ env.WHEN }}
        id: build
        uses: ./ # This is the action defined in this repo.
        with:
          product_name: ${{ inputs.product_name }}
          product_version: ${{ inputs.product_version }}
          go_version: ${{ inputs.go_version }}
          os: ${{ inputs.os }}
          arch: ${{ inputs.arch }}
          instructions: ${{ inputs.instructions }}
        continue-on-error: true
      - if: inputs.assert == 'success'
        run: ./scripts/gha_assert_success "${{ steps.build.outcome }}"
      - if: inputs.assert == 'failure'
        run: ./scripts/gha_assert_failure "${{ steps.build.outcome }}"
