name: Matrix Example
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { os: darwin, arch: amd64 }
          - { os: darwin, arch: arm64 }
          - { os: linux, arch: amd64 }
          - { os: linux, arch: amd64 }
          - { os: windows, arch: amd64 }
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: hashicorp/actions-reproducible-build@main
        with:
          product_name: example-app
          product_version: 1.2.3
          go_version: 1.18
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          instructions: |-
            cd ./testdata/example-app
            go build \
              -trimpath \
              -buildvcs=false \
              -o "$BIN_PATH" \
              -ldflags "
                -X 'main.Version=$PRODUCT_VERSION'
                -X 'main.Revision=$PRODUCT_REVISION'
                -X 'main.RevisionTime=$PRODUCT_REVISION_TIME'
              "
