name: Test Verify

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!dev/**'
      - '!action.yml'

jobs:

  macos:
    uses: ./.github/workflows/self-test-suite-verify.yml
    with:
      runner: macos-latest

  linux:
    uses: ./.github/workflows/self-test-suite-verify.yml
    with:
      runner: ubuntu-latest
