name: Test

on:
  push:
    paths:
      - "**"
      - "!**.md"
      - "!dev/**"
      - "!verify/**"
      - "!action.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: super-linter/super-linter@b92721f792f381cedc002ecdbb9847a15ece5bb8 # v7.1.0

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
          cache: false
      - run: make test/go
