name: Test

on:
  push:
    paths:
      - "**"
      - "!**.md"
      - "!dev/**"
      - "!verify/**"
      - "!action.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b # v7.0.0

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          cache: false
      - run: make test/go
