name: Test

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: github/super-linter@v4

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: make test/go

  macos:
    uses: ./.github/workflows/self-test-suite.yml
    with:
      runner: macos-latest

  linux:
    uses: ./.github/workflows/self-test-suite.yml
    with:
      runner: ubuntu-latest

  macos-verify:
    uses: ./.github/workflows/self-test-suite-verify.yml
    with:
      runner: macos-latest

  linux-verify:
    uses: ./.github/workflows/self-test-suite-verify.yml
    with:
      runner: ubuntu-latest
