name: Test

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!dev/**'
      - '!verify/**'
      - '!action.yml'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: github/super-linter@4e51915f4a812abf59fed160bb14595c0a38a9e7 # v6

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
      - run: make test/go
