name: Test

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!dev/**'
      - '!verify/**'
      - '!action.yml'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: github/super-linter@v4

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: make test/go
