name: Test Build

on: [push]

jobs:

  macos:
    uses: ./.github/workflows/self-test-suite.yml
    with:
      runner: macos-latest

  linux:
    uses: ./.github/workflows/self-test-suite.yml
    with:
      runner: ubuntu-latest
