name: Test

on: [push]

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Invoke Action
        uses: ./ # This is the action defined in this repo.
        with:
          go_version: 1.17
          product_version: 1.0.0
          os: linux
          arch: amd64
          package_name: dummy-app
          instructions: |-
            cd testdata/dummy-app
            go build -o "$TARGET_DIR/$BIN_NAME" .
