name: Test

on:
  push:
    paths:
      - "**"
      - "!**.md"
      - "!dev/**"
      - "!verify/**"
      - "!action.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: super-linter/super-linter@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d # v7.2.1

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod
          cache: false
      - run: make test/go
