name: Test

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!dev/**'
      - '!verify/**'
      - '!action.yml'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: github/super-linter@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 1.18
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: make test/go
