name: Test

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!dev/**'
      - '!verify/**'
      - '!action.yml'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: github/super-linter@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: go.mod
      - run: make test/go
